# Generated by Django 6.1 on 2026-09-05 05:22

from django.db import migrations, models


def remove_duplicate_daily_visitors(apps, schema_editor):
    """Make the new uniqueness rule safe for databases with old duplicate rows."""
    UniqueVisitor = apps.get_model('analytics', 'UniqueVisitor')
    duplicates = (
        UniqueVisitor.objects.values('ip_address', 'date')
        .annotate(count=models.Count('id'))
        .filter(count__gt=1)
    )
    for duplicate in duplicates:
        rows = UniqueVisitor.objects.filter(
            ip_address=duplicate['ip_address'], date=duplicate['date'],
        ).order_by('id')
        rows.exclude(id=rows.first().id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ('-timestamp',), 'verbose_name': 'page view', 'verbose_name_plural': 'page views'},
        ),
        migrations.AlterModelOptions(
            name='uniquevisitor',
            options={'ordering': ('-date',), 'verbose_name': 'daily unique visitor', 'verbose_name_plural': 'daily unique visitors'},
        ),
        migrations.AlterField(
            model_name='pageview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='path',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='uniquevisitor',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.RunPython(remove_duplicate_daily_visitors, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='uniquevisitor',
            constraint=models.UniqueConstraint(fields=('ip_address', 'date'), name='unique_visitor_per_day'),
        ),
    ]
