# Generated by Django 5.0.6 on 2026-08-25 04:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_certificate_file_alter_blog_id_alter_certificate_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional post title', max_length=250, null=True)),
                ('content', models.TextField(help_text='Share a story, thought or life update')),
                ('image', models.ImageField(blank=True, help_text='Optional photo/image for the post', null=True, upload_to='feed/')),
                ('location', models.CharField(blank=True, help_text='e.g. Tashkent, Uzbekistan', max_length=150, null=True)),
                ('mood_emoji', models.CharField(blank=True, help_text='e.g. ☕, 💻, 🚀, 🏔️', max_length=20, null=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feed Post',
                'verbose_name_plural': 'Feed Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Anonymous Reader', max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.feedpost')),
            ],
            options={
                'verbose_name': 'Feed Comment',
                'verbose_name_plural': 'Feed Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
