# Generated by Django 6.1 on 2026-08-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_talk'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional blog cover image', null=True, upload_to='blog/'),
        ),
    ]
