# Generated by Django 6.1 on 2026-08-28 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='video',
            field=models.FileField(blank=True, help_text='Optional video for the post (MP4, MOV, AVI, MKV, WEBM)', null=True, upload_to='feed/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv', 'webm'])]),
        ),
    ]
