# Generated by Django 6.1 on 2026-09-07 06:13

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_feedpost_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog post', 'verbose_name_plural': 'Blog posts'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order', '-id'], 'verbose_name': 'Education entry', 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='feedcomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Feed comment', 'verbose_name_plural': 'Feed comments'},
        ),
        migrations.AlterModelOptions(
            name='feedpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Feed post', 'verbose_name_plural': 'Feed posts'},
        ),
        migrations.AlterModelOptions(
            name='voluntaryactivity',
            options={'ordering': ['order', '-id'], 'verbose_name': 'Voluntary activity', 'verbose_name_plural': 'Voluntary activities'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['order', '-id'], 'verbose_name': 'Work experience', 'verbose_name_plural': 'Work experience'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='Landscape images work best. Around 1200x630 pixels is ideal.', null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.CharField(blank=True, help_text='Set automatically on first save, e.g. "3 days ago".', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(help_text='e.g. "BSc Computer Science"', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(help_text='School or university name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='period',
            field=models.CharField(help_text='e.g. "2020 — 2024"', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='One point per line. Start a line with "-" for a bullet.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, help_text='GitHub, demo or live URL.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='period',
            field=models.CharField(blank=True, help_text='e.g. "2024"', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='talk',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='talk',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='video',
            field=models.FileField(help_text='MP4 plays everywhere. MOV, AVI, MKV and WEBM are accepted but may not play in every browser.', upload_to='talks/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True, help_text='One duty or achievement per line. Start a line with "-" for a bullet.'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='period',
            field=models.CharField(help_text='e.g. "Jan 2024 — Present"', max_length=100),
        ),
    ]
