# Generated by Django 6.1 on 2026-09-07 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blog_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Backend", "Data", "DevOps".', max_length=80)),
                ('tagline', models.CharField(blank=True, help_text='Optional one-liner shown next to the group name.', max_length=120)),
                ('order', models.IntegerField(default=0, help_text='Lowest number sits closest to the centre of the map.')),
            ],
            options={
                'verbose_name': 'Skill group',
                'verbose_name_plural': 'Skill groups',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Learning'), (2, 'Working knowledge'), (3, 'Comfortable'), (4, 'Strong'), (5, 'Core strength')], default=3, help_text='Sets how large the node is drawn and how many dots are filled.')),
                ('years', models.CharField(blank=True, help_text='Optional, e.g. "4y". Shown next to the skill.', max_length=20)),
                ('is_core', models.BooleanField(default=False, help_text='Draws the node filled in, for the few skills you lead with.', verbose_name='Highlight')),
                ('order', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='blog.skillgroup')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
