# Generated by Django 6.1 on 2026-09-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_seed_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='is_core',
            field=models.BooleanField(default=False, help_text='Marks the skill CORE on the CV, for the few you lead with.', verbose_name='Highlight'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Learning'), (2, 'Working knowledge'), (3, 'Comfortable'), (4, 'Strong'), (5, 'Core strength')], default=3, help_text='Sets how far the level bar is filled on the CV.'),
        ),
        migrations.AlterField(
            model_name='skillgroup',
            name='order',
            field=models.IntegerField(default=0, help_text='Lowest number comes first in the list.'),
        ),
    ]
