# Generated by Django 6.1 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_refresh_technical_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='location',
            field=models.CharField(
                blank=True,
                help_text='e.g. Karshi, Uzbekistan',
                max_length=150,
                null=True,
            ),
        ),
    ]
